name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Set AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: echo "AWS credentials set"

    # Initialisation de Terraform
    - name: Terraform Init
      run: terraform init

    # Validation de la configuration Terraform
    - name: Terraform Validate
      run: terraform validate

    # (Optionnel) Linting avec tflint
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    - name: Run TFLint
      run: tflint

    # Création du plan Terraform
    - name: Terraform Plan
      run: terraform plan

    # Application de la configuration Terraform
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve

